# Generated by Django 4.2.4 on 2023-08-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MalePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.PositiveIntegerField()),
                ("player_url", models.CharField(max_length=2000)),
                ("fifa_version", models.PositiveIntegerField()),
                ("fifa_update", models.PositiveIntegerField()),
                ("fifa_update_date", models.DateField()),
                ("short_name", models.CharField(max_length=50)),
                ("long_name", models.CharField(max_length=100)),
                ("player_positions", models.CharField(max_length=100)),
                ("overall", models.PositiveIntegerField()),
                ("potential", models.PositiveIntegerField()),
            ],
        ),
    ]
